name: Build flutter app

on:
  workflow_call:
    inputs:
      app_version:
        required: true
        type: string
        description: "App version"
        default: "1.0.0"
      build_number:
        required: true
        type: string
        description: "Build number"
        default: "1"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      APP_VERSION: ${{ inputs.app_version }}
      BUILD_NUMBER: ${{ inputs.build_number }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0"
          cache: true

      - name: Setup Golang
        uses: actions/setup-go@v5
        with:
          go-version-file: torrent/src/go.mod
          cache-dependency-path: torrent/src/go.sum

      - name: Patch Linux
        if: runner.os == 'Linux'
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libglu1-mesa clang cmake ninja-build libgtk-3-dev libmpv-dev mpv libfuse2
          version: 1.0

      - name: Reinstall FUSE
        if: runner.os == 'Linux'
        run: sudo apt-get install -y --reinstall libfuse2

      - name: Fix missing libblas.so.3 and liblapack.so.3
        if: runner.os == 'Linux'
        run: |
          sudo find /usr/lib -name libblas.so.3
          sudo ln -s /usr/lib/x86_64-linux-gnu/blas/libblas.so.3 /usr/lib/x86_64-linux-gnu/
          sudo ln -s /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3 /usr/lib/x86_64-linux-gnu/

        # Run flutter doctor to verify dependencies
      - name: Flutter doctor
        run: flutter doctor --verbose
        shell:
          bash

          # Build for each platform
      - name: Build for Linux
        if: runner.os == 'Linux'
        run: scripts/build-linux.sh ${{ env.APP_VERSION }} ${{ env.BUILD_NUMBER }}
        shell: bash

      # Upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tor_player_${{ runner.os }}
          path: |
            build/*.AppImage
            build\*.exe
            build/*.dmg
            build/*.apk
            build/*.pkg
