name: Test

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
    build:
        uses: ./.github/workflows/build.yml
        with:
            app_version: "1.0.0"
            build_number: "1"